In [11]:
from latent_geometry.mapping.sphere_immersion import SphereImmersion

import numpy as np

## sphere immersion class

In [12]:
sphere_immersion = SphereImmersion()

In [13]:
x = np.array([1, np.pi / 2])
sphere_immersion(x)

array([5.40302306e-01, 8.41470985e-01, 6.12323400e-17])

In [14]:
J = sphere_immersion.jacobian(x)
print(J.shape)
J

(3, 2)


array([[-8.41470985e-01,  3.30839745e-17],
       [ 5.40302306e-01,  5.15252374e-17],
       [ 0.00000000e+00, -1.00000000e+00]])

DM should be 0, as the curvature is the same at every point on the sphere!

In [15]:
DM = sphere_immersion.metric_matrix_derivative(x)
print(DM.shape)
DM

(2, 2, 2)


array([[[0.00000000e+00, 1.22464680e-16],
        [0.00000000e+00, 0.00000000e+00]],

       [[0.00000000e+00, 0.00000000e+00],
        [6.84227766e-49, 0.00000000e+00]]])

## pullback metric class

In [16]:
from latent_geometry.metric.euclidean import EuclideanPullbackMetric

In [17]:
sphere_pullback_metric = EuclideanPullbackMetric(sphere_immersion)

TypeError: __init__() missing 1 required positional argument: 'mapping'

In [ ]:
sphere_pullback_metric.metric_matrix(x)

array([[ 1.00000000e+00, -2.24430224e-33],
       [-2.24430224e-33,  1.00000000e+00]])

In [ ]:
sphere_pullback_metric.metric_matrix_derivative(x)

array([[[0.00000000e+00, 1.22464680e-16],
        [0.00000000e+00, 0.00000000e+00]],

       [[0.00000000e+00, 0.00000000e+00],
        [6.84227766e-49, 0.00000000e+00]]])

In [ ]:
v = np.array([1.0, 0.0])

In [ ]:
sphere_pullback_metric.acceleration(position=x, velocity=v)

NotImplementedError: 